version: '2'
services:
  gitlab:
    image: 'docker.io/gitlab/gitlab-ce:11.1.1-ce.0'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.lianwiki.cn'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "xx@xx.com"
        gitlab_rails['smtp_password'] = "your_password"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'xx@xx.com'
        gitlab_rails['smtp_domain'] = "exmail.qq.com"
        gitlab_rails['gitlab_email_from'] = 'xx@xx.com'
        gitlab_rails['gitlab_email_reply_to'] = 'xx@xx.com'
    ports:
      - '8888:80'
      - '8443:443'
      - '22:22'
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
  runner:
    image: 'docker.io/gitlab/gitlab-runner:latest'
    restart: always
    depends_on:
      - gitlab
    volumes:
      - '/data/gitlab-runner/config:/etc/gitlab-runner'
  runner-register:
    image: 'docker.io/gitlab/gitlab-runner:latest'
    restart: 'no'
    command: register --locked=false
    environment:
      - CI_SERVER_URL=http://git.lianwiki.cn/
      - REGISTRATION_TOKEN=biu5x-HBoTNaFN-ckZCu
      - RUNNER_NAME=worker
      - REGISTER_NON_INTERACTIVE=true
      - RUNNER_EXECUTOR=shell
    volumes:
      - '/data/gitlab-runner/config:/etc/gitlab-runner'